/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export const Shoe = (props) => {
  const { nodes, materials } = useGLTF("/shoe.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Shoe.geometry}
        material={materials.phong1SG}
        position={[0.002, 0.076, 0.005]}
        scale={0.149}
      />
    </group>
  );
};

useGLTF.preload("/shoe.glb");
